### ISSUE TITLE
AWS IoT Greengrass 2.2.0 Release

### ISSUE THREAD

**Issue by gadams999** [aws-greengrass/aws-greengrass-docker#12]
**Describe the bug**
Current release only supports AWS IoT Greengrass 2.1.0, the latest released version of Greengrass is 2.2.0

**To Reproduce**
Download main branch and build.

**Expected behavior**
I download from main branch and build. At that point I have a container file for 2.2.0.

**Actual behavior**
Greengrass 2.1.0 is build and used.

**Screenshots**
n/a

**Docker Inspect and Logs**
n/a

**Environment**
 - OS:
 - JDK version:
 - Greengrass version
 - Docker version
 - Docker image version
 - `docker-compose` version
 - Output of `uname -a`
 - Output of `cat /etc/os-release` or its equivalent

**Additional context**
- An authoritative has file for the Greengrass 2.2.0.zip file is needed
- A complete series of tests should be performed before release

**Comment by kucnavya** [comment]
2.2.0 release is now available https://github.com/aws-greengrass/aws-greengrass-docker/releases/tag/v2.2.0
