### ISSUE TITLE
Support for Python3.9

### ISSUE THREAD

**Issue by K-AWS** [aws-greengrass/aws-greengrass-docker#24]
https://github.com/aws-greengrass/aws-greengrass-docker/blob/1c19905c2afdb72c209f00755b9f5eb16310a403/Dockerfile#L40

Can we add support for Python3.9?

**Comment by Xuqing888** [comment]
For testing purpose, next release we will add python3.9 support along with it together

**Comment by lpatterson-humanetics** [comment]
Any update on this?  Python has moved along and greengrass is stuck in the past.  Will any new release be happening with this?

**Comment by MikeDombo** [comment]
We recommend that all customers use this dockerfile provided here as a base to start from. If you need a newer version of Python, please edit the dockerfile to install the version that you need.
