### ISSUE TITLE
Enable provisioning via Environment Variables

### ISSUE THREAD

**Issue by kaidobit** [aws-greengrass/aws-greengrass-docker#30]
**Feature Description**
Provisioning Greengrass V2 locally without docker is possible when the AWS credentials (Access key ID and Secret Access Key) as well as the configured default region are exposed via environment variables.
This is useful when working with tools like `aws-vault`, which expose AWS credentials and region via environment variables.

**Use Case**
Be able to retrieve AWS credentials from a secret store and configured default region via `aws-vault` and provision Greengrass V2 in docker using [temporary credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html).

**Proposed Solution**
Introduce new environment variables:
- AWS_REGION
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_SESSION_TOKEN

In addition to retrieving credentials only from a [mounted config-file](https://github.com/aws-greengrass/aws-greengrass-docker/blob/f53d0fccdcdb5626f311489b5a8281c047616739/README.md?plain=1#L40), also check if there are environment variables (AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN) exposed and use those.

The priority to use either the config file or environment variables first for provisioning, doesn't matter for me.

Make sure to unset the secret environment variables when provisioning is finished for security reasons (same behavior as when provisioning locally `aws-vault exec <PROFILENAME> -- java -jar ... Greengrass.jar`).

When running the container, the `docker run`- or the `docker-compose up`-command need to incorporate the variables:

`docker run -e “AWS_REGION=${AWS_REGION}” -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -e "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"...`

or
```
services:
  greengrass:
    environment:
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
```
The `docker run`- or `docker-compose up`-command then needs to be wrapped with aws-vault:

`aws-vault exec <PROFILE> -- docker run ...`
`aws-vault exec <PROFILE> -- docker-compose up`

**Other**
- [aws-vault](https://github.com/99designs/aws-vault), Installation and Quick Start in README
- [How `aws-vault `works](https://github.com/99designs/aws-vault/blob/3a2136a447bfc65c70a802fddede9d11b6e0ab10/README.md?plain=1#L68)
- useful command during development: `aws-vault exec <PROFILENAME> -- env | grep AWS_`
- [code location to change](https://github.com/aws-greengrass/aws-greengrass-docker/blob/f53d0fccdcdb5626f311489b5a8281c047616739/greengrass-entrypoint.sh#L21)

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by avipinku** [comment]
Hi, thank you for submitting this.

Unfortunately, setting secrets as Docker environment variables is not recommended, since Docker environment variables are immutable for the life of the container, and hence are easily exposed and retrievable as plaintext using `docker inspect`. I.e., if you run `docker inspect <container ID>`, you should be able to easily see these exposed credentials, which is a security risk.

The secure alternative here is to use Docker Secrets, which may or may not fit your use case. [Here's a good explanation](https://earthly.dev/blog/docker-secrets/).

**Comment by kaidobit** [comment]
I don't see how a unencrypted file which is never deleted more secure.
Also this approach would use temporary credentials (which doesn't mean there could be perma creds used) which have a TTL.

**Comment by xsahban** [comment]
Hi @kaidobit @avipinku 
I have created following PR https://github.com/aws-greengrass/aws-greengrass-docker/pull/37 for this issue

Please give a review and your inputs.

**Comment by junfuchen99** [comment]
Thanks @xsahban for the contribution. Closing this issue since https://github.com/aws-greengrass/aws-greengrass-docker/pull/37 has been merged.
