### ISSUE TITLE
Provide instructions to build for `aarch64`

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-docker#31]
**Feature Description**
Provide instructions to build the container image for `aarch64`

**Use Case**
To run this container on ARM machines, and on Mac M1 without the need of an emulator

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by junfuchen99** [comment]
Hello @massi-ang,

Thanks for the feature request. This is currently on our list of improvements we're tracking. We will update here once we make progress.

**Comment by MikeDombo** [comment]
Hi @massi-ang,

When running docker on an arm machine, a mac m1 for example, it will build for aarch64 automatically with no changes whatsoever.

Example output from `docker image inspect`
```
"Architecture": "arm64",
        "Variant": "v8",
        "Os": "linux",
```

**Comment by MikeDombo** [comment]
Please reopen if there is an issue with this.
