### ISSUE TITLE
Bump to nucleus 2.8.0 

### ISSUE THREAD

**Issue by arulrajnet** [aws-greengrass/aws-greengrass-docker#33]
Upgrade to 2.8.0 https://github.com/aws-greengrass/aws-greengrass-nucleus/releases/tag/v2.8.0

**Comment by kucnavya** [comment]
Thank you for reaching out, Arul. We are working on updating the docker release, but I do not have a timeline for you. I also do not have a timeline for accepting a PR for this change unfortunately. 
If you would like to use the newer version now, we do suggest that you build your own Docker image based on the one provided in this repository.

**Comment by kucnavya** [comment]
Hi Chris. Thank you for your patience. 
We have an extensive testing process that the Docker image is validated against. Although the PR is quite small, we would not feel confident of accepting it without establishing the reliability of the docker image it yields. And at this time we do not have an exact timeline for when we would be able make this change. I apologize for the inconvenience. 
Please feel free to fork the repository, update the Greengrass version and build your own Docker image.

**Comment by cody2094** [comment]
@kucnavya has there been any movement on this issue?

**Comment by alter-mage** [comment]
Hi Cody, thanks for reaching out.
We are not actively developing on Docker and it is unlikely we will be making any changes to this repository.
Please feel free to fork the repository and make any changes needed to build your own Greengrass Docker images.
