### ISSUE TITLE
greengrass-cli inside docker container

### ISSUE THREAD

**Issue by HaimMyasnikoff** [aws-greengrass/aws-greengrass-docker#40]
**Describe the bug**
is it possible to use greengrass-cli inside docker container which was created from aws-greengrass/aws-greengrass-docker repositry?

https://docs.aws.amazon.com/greengrass/v2/developerguide/gg-cli-deployment.html

can you provide CLI examples of such usage?

**Comment by MikeDombo** [comment]
Use docker exec to execute commands inside a container which exists: https://docs.docker.com/engine/reference/commandline/exec/
