### ISSUE TITLE
greengrass-cli dont start inside docker container

### ISSUE THREAD

**Issue by HaimMyasnikoff** [aws-greengrass/aws-greengrass-docker#41]
**Describe the bug**

greengrass-cli can't start inside docker container

user@host:# docker exec -it <container-id> greengrass-cli
OCI runtime exec failed: exec failed: unable to start container process: exec: "greengrass-cli": executable file not found in $PATH: unknown

according to documentation https://docs.aws.amazon.com/greengrass/v2/developerguide/install-gg-cli.html
DEPLOY_DEV_TOOLS=true
PROVISION=true
should be enough for greengrass-cli installation but it wasn't installed

**To Reproduce**

Docker run command:

```
docker run --rm --init -d --name greengrass-test \
 -v /home/user/IOT/config:/tmp/config/:ro \
 --env-file .env \
 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
 -p 8883 greengrass:3
```

Content of .env file:

```
GGC_ROOT_PATH=/greengrass/v2
AWS_REGION=eu-central-1
PROVISION=true
COMPONENT_DEFAULT_USER=ggc_user:ggc_group
TES_ROLE_ALIAS_NAME=TokenExchangeRoleAlias
DEPLOY_DEV_TOOLS=true
THING_NAME=test-thing
THING_GROUP_NAME=thing-group1
TES_ROLE_NAME=TokenExchangeRole
LOG_LEVEL=DEBUG
```

**Expected behavior**
Run commands via
docker exec -it <container-id> greengrass-cli

**Docker Inspect and Logs**
No new records in /greengrass/v2/logs/greengrass.log

**Environment**
 GREENGRASS_RELEASE_VERSION=2.10.3

**Comment by MikeDombo** [comment]
Hello,

`greengrass-cli` is not the correct command to run. You must wait for the deployment to complete, then execute the CLI following the instructions: https://docs.aws.amazon.com/greengrass/v2/developerguide/gg-cli-reference.html

`/greengrass/v2/bin/greengrass-cli`
