### ISSUE TITLE
error: "unary operator expected" error returned from greengrass-entrypoint.sh

### ISSUE THREAD

**Issue by deadprogram** [aws-greengrass/aws-greengrass-docker#49]
**Describe the bug**

When trying to `docker run` the locally built container, the bash script used for the `ENTRYPOINT` in the `Dockerfile` displays the following error in the output:

```shell
Nucleus start set to false, exiting...
/greengrass-entrypoint.sh: line 91: [: =: unary operator expected
```
**To Reproduce**
After building the container, executing `docker run` with that container results in the above error.

**Expected behavior**
For `docker run` to be able to succeed.

**Actual behavior**
Tell us what actually happened.

The container started, but did not correctly connect to AWS as expected to provision a new device.

**Screenshots**

**Docker Inspect and Logs**
If available, add `docker_container.log` and `docker_inspect.json`.

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 macOS Sonoma 14.5
 
- JDK version:
unknown
 - Greengrass version
latest `main` branch from repo.
 - Docker version 
Docker Desltop for macOS 4.30.0
 - Docker image version
 - `docker-compose` version - n/a
 - Output of `uname -a`:
 `Darwin Rons-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64`
 - Output of `cat /etc/os-release` or its equivalent

**Additional context**

None

**Comment by aws-kevinrickard** [comment]
Thanks for submitting the issue and fix! Closing the issue, let me know if there is anything still unresolved.
