### ISSUE TITLE
Standardize on Apache 2.0 license

### ISSUE THREAD

**Issue by oaustegard** [aws-greengrass/aws-greengrass-docker#9]
**Feature Description**
Standardize licensing on Apache 2.0

**Use Case**
Simplifying corporate approval to use AWS Greengrass

**Proposed Solution**
Either switch the license for aws-greengrass-docker from the MIT license to Apache 2.0 or dual license the component

**Other**
* [x] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi Oskar,
These docker templates are licensed as MIT-0 as MIT-0 is even more permissive than Apache 2. The license only applies to the contents of the repository, meaning that if you were to use our pre-built images those are not subject to the MIT-0 license, but the Greengrass license. https://greengrass-release-license.s3.us-west-2.amazonaws.com/greengrass-license-v1.pdf

**Comment by oaustegard** [comment]
Understood, but lawyers are a persnickety bunch and as such might be happier if they could apply the Apache 2.0 license to this as well, just so that they don't have to review Yet Another License, even if that would make use (slightly) more restrictive.

**Comment by oaustegard** [comment]
PS! Is the Greengrass license linked anywhere but from the general AWS Service Terms? [Hiding out at position 55](https://aws.amazon.com/service-terms/#55._AWS_Greengrass) is hardly handy...

**Comment by MikeDombo** [comment]
Yes, it is also mentioned in our documentation: https://docs.aws.amazon.com/greengrass/v2/developerguide/getting-started.html#install-greengrass-v2

**Comment by oaustegard** [comment]
Ah, there it is in the last search result... https://docs.aws.amazon.com/search/doc-search.html?searchPath=documentation-guide&searchQuery=license&this_doc_product=AWS%20IoT%20Greengrass&this_doc_guide=Developer%20Guide,%20Version%202#facet_doc_product=AWS%20IoT%20Greengrass&facet_doc_guide=Developer%20Guide,%20Version%202  (I failed to scroll to page 2 in my prior search)
